# This is a basic workflow to help you get started with Actions

name: Build macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Run make script
        run: npm run make
