name: Publish macOS

on:
  repository_dispatch:
    types: [trigger-publish]

jobs:
  publish-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package

      - name: Decode certificate
        id: decode_certificate
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'certificate.p12'
          encodedString: ${{ secrets.MACOS_CERTIFICATE }}

      - name: Code sign
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          security create-keychain -p tmp-password build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p tmp-password build.keychain
          security import ${{ steps.decode_certificate.outputs.filePath }} -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k tmp-password build.keychain
          /usr/bin/codesign --force -s FPEMKZSSJC ./out/Negative-darwin-x64/Negative.app/Contents/Frameworks/Negative\ Helper.app -v
          /usr/bin/codesign --force -s FPEMKZSSJC ./out/Negative-darwin-x64/Negative.app -v

      - name: Make and publish to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
