name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  build-macos:
    runs-on: macos-latest

    strategy:
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install

      - name: Run make script
        run: npm run make

      - name: Deploy assets to GitHub Release
        if: ${{ success() }}
        run: npm run publish
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install

      - name: Run make script
        run: npm run make

      - name: Deploy assets to GitHub Release
        if: ${{ success() }}
        run: npm run publish
